{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "akd-api.fullname" . }}
  labels:
    {{- include "akd-api.labels" . | nindent 4 }}
  {{- if .Values.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "akd-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ include "akd-api.fullname" . }}-tls
  {{- end }}
{{- end }}
