apiVersion: v1
kind: Service
metadata:
  name: {{ include "akd-inference.fullname" . }}
  labels:
    {{- include "akd-inference.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11434
  selector:
    {{- include "akd-inference.labels" . | nindent 4 }}
